# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chater', '0002_remove_messages_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file_path',
            field=models.CharField(default='no', max_length=500),
            preserve_default=False,
        ),
    ]
