# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chater', '0003_messages_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file_path',
            field=models.FileField(null=True, upload_to=b'documents/'),
        ),
    ]
